[note]
filename = "{{slug title}}"
template = "default.md"

[group.daily]
paths = ["journal"]

[group.daily.note]
filename = "{{date now '%Y-%m-%d'}}"
template = "daily.md"

[format.markdown]
link-format = "wiki"
hashtags = true
colon-tags = false
multiword-tags = false

[lsp.diagnostics]
dead-link = "hint"

[alias]
ls = "zk list $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
path = "zk list --quiet --format {{path}} --delimiter , $@"
conf = '$EDITOR "$ZK_NOTEBOOK_DIR/.zk/config.toml"'
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'
